#!/usr/bin/env bash
# Run Hyphae + Llama-8B-local + 5×DO-Inference all on TriviaQA-150 corpus.
set -uo pipefail

cd "/Volumes/My Book/Documents/hyphae-v2/bench/baseline-llm-rag"

if [[ -z "${DO_INFERENCE_KEY:-}" ]]; then
    echo "ERROR: DO_INFERENCE_KEY env var required" >&2
    exit 1
fi

CORPUS="corpus-triviaqa-150.json"
HW_TAG="laptop-triviaqa"

# 1. Score Hyphae output (already generated by Rust binary)
echo "=== [1/19] hyphae score ==="
date +%H:%M:%S
uv run python -m baseline_llm_rag.score_hyphae \
    --hyphae-output hyphae-results-triviaqa.json \
    --output "results/v0.1-${HW_TAG}-hyphae-none.json" 2>&1 | tail -1

# 2-4. Llama-8B local 3 modes
i=1
for MODE in oracle rag strong-rag; do
    i=$((i + 1))
    echo ""
    echo "=== [${i}/19] llama-8B-local :: $MODE ==="
    date +%H:%M:%S
    uv run baseline-llm-rag --mode "$MODE" \
        --corpus "$CORPUS" \
        --output "results/v0.1-${HW_TAG}-${MODE}.json" 2>&1 | tail -2 \
        || echo "  ✗ FAILED: llama-8B-local :: $MODE"
done

# 5-19. Multi-LLM 5×3 via DO Inference
MODELS=(
    "llama3.3-70b-instruct"
    "anthropic-claude-4.6-sonnet"
    "openai-gpt-4.1"
    "deepseek-v4-pro"
    "router:celiums-conversation"
)
for MODEL in "${MODELS[@]}"; do
    TAG="${MODEL//:/-}"
    for MODE in oracle rag strong-rag; do
        i=$((i + 1))
        OUT="results/v0.1-${HW_TAG}-doinf-${TAG}-${MODE}.json"
        echo ""
        echo "=== [${i}/19] $MODEL :: $MODE ==="
        date +%H:%M:%S
        uv run baseline-llm-rag --mode "$MODE" \
            --corpus "$CORPUS" \
            --output "$OUT" \
            --llm-backend do-inference \
            --model "$MODEL" 2>&1 | tail -2 \
            || echo "  ✗ FAILED: $MODEL :: $MODE"
    done
done

echo ""
echo "=== TRIVIAQA RUN DONE ==="
date +%H:%M:%S
ls -lh "results/v0.1-${HW_TAG}-"*.json
